FROM pytorch/pytorch
ENV DOCKER_RUNNING=True
ENV REDIS_IP=10.24.24.32 REDIS_PORT=6379
WORKDIR /src
COPY src/server/requirements.txt .
RUN python -m pip install -r requirements.txt
COPY docker/secure_agg_party_entrypoint.sh .
COPY src .
CMD ["bash", "./secure_agg_party_entrypoint.sh"]
