# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.secure_agg_pb2 as secure__agg__pb2


class SecureAggPartyServiceStub(object):
    """Client -> party and flo_server -> party control plane. See
    docs/secure_aggregation/proto_contract.md for the full contract and the
    round_id replay/mix-up-guard rationale.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitShare = channel.unary_unary(
                '/SecureAggPartyService/SubmitShare',
                request_serializer=secure__agg__pb2.SubmitShareRequest.SerializeToString,
                response_deserializer=secure__agg__pb2.SubmitShareAck.FromString,
                )
        self.RunAggregationRound = channel.unary_unary(
                '/SecureAggPartyService/RunAggregationRound',
                request_serializer=secure__agg__pb2.RunAggregationRoundRequest.SerializeToString,
                response_deserializer=secure__agg__pb2.RunAggregationRoundResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/SecureAggPartyService/HealthCheck',
                request_serializer=secure__agg__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=secure__agg__pb2.HealthCheckResponse.FromString,
                )


class SecureAggPartyServiceServicer(object):
    """Client -> party and flo_server -> party control plane. See
    docs/secure_aggregation/proto_contract.md for the full contract and the
    round_id replay/mix-up-guard rationale.
    """

    def SubmitShare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunAggregationRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecureAggPartyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitShare': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitShare,
                    request_deserializer=secure__agg__pb2.SubmitShareRequest.FromString,
                    response_serializer=secure__agg__pb2.SubmitShareAck.SerializeToString,
            ),
            'RunAggregationRound': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAggregationRound,
                    request_deserializer=secure__agg__pb2.RunAggregationRoundRequest.FromString,
                    response_serializer=secure__agg__pb2.RunAggregationRoundResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=secure__agg__pb2.HealthCheckRequest.FromString,
                    response_serializer=secure__agg__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SecureAggPartyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecureAggPartyService(object):
    """Client -> party and flo_server -> party control plane. See
    docs/secure_aggregation/proto_contract.md for the full contract and the
    round_id replay/mix-up-guard rationale.
    """

    @staticmethod
    def SubmitShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecureAggPartyService/SubmitShare',
            secure__agg__pb2.SubmitShareRequest.SerializeToString,
            secure__agg__pb2.SubmitShareAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunAggregationRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecureAggPartyService/RunAggregationRound',
            secure__agg__pb2.RunAggregationRoundRequest.SerializeToString,
            secure__agg__pb2.RunAggregationRoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecureAggPartyService/HealthCheck',
            secure__agg__pb2.HealthCheckRequest.SerializeToString,
            secure__agg__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SecureAggPeerServiceStub(object):
    """Party <-> party. Used ONLY by backends whose inter-party protocol is
    implemented as gRPC calls between this repo's own party processes (e.g.
    backend_simulator.py). Backends with their own wire protocol (e.g.
    backend_hpmpc.py's raw TCP/TLS sockets between spawned binaries, Phase 3)
    do not use this service at all — it is not part of the
    SecureAggregationBackend interface contract, just a convenience for
    backends implemented in pure Python.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFinalShare = channel.unary_unary(
                '/SecureAggPeerService/GetFinalShare',
                request_serializer=secure__agg__pb2.GetFinalShareRequest.SerializeToString,
                response_deserializer=secure__agg__pb2.GetFinalShareResponse.FromString,
                )


class SecureAggPeerServiceServicer(object):
    """Party <-> party. Used ONLY by backends whose inter-party protocol is
    implemented as gRPC calls between this repo's own party processes (e.g.
    backend_simulator.py). Backends with their own wire protocol (e.g.
    backend_hpmpc.py's raw TCP/TLS sockets between spawned binaries, Phase 3)
    do not use this service at all — it is not part of the
    SecureAggregationBackend interface contract, just a convenience for
    backends implemented in pure Python.
    """

    def GetFinalShare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecureAggPeerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFinalShare': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFinalShare,
                    request_deserializer=secure__agg__pb2.GetFinalShareRequest.FromString,
                    response_serializer=secure__agg__pb2.GetFinalShareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SecureAggPeerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecureAggPeerService(object):
    """Party <-> party. Used ONLY by backends whose inter-party protocol is
    implemented as gRPC calls between this repo's own party processes (e.g.
    backend_simulator.py). Backends with their own wire protocol (e.g.
    backend_hpmpc.py's raw TCP/TLS sockets between spawned binaries, Phase 3)
    do not use this service at all — it is not part of the
    SecureAggregationBackend interface contract, just a convenience for
    backends implemented in pure Python.
    """

    @staticmethod
    def GetFinalShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecureAggPeerService/GetFinalShare',
            secure__agg__pb2.GetFinalShareRequest.SerializeToString,
            secure__agg__pb2.GetFinalShareResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
